
services:
  tata_power_fastapi:
    build: .
    container_name: tata_power_fastapi
    restart: always
    ports:
      - "7001:7001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@172.18.7.91:5432/Tata_Power
    volumes:
      - ./app:/app
    networks:
      - app-network
  
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  minio_data:
